ci:
  autofix_prs: false
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.5
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
        exclude: ".*(.fits|.fts|.fit|.nc|.gz|.txt|tca.*|extern.*|.rst|.md|docs/conf.py)$"
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--sp','setup.cfg']
        exclude: ".*(.fits|.fts|.fit|.nc|.gz|.txt|tca.*|extern.*|.rst|.md|docs/conf.py)$"
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ".*(.fits|.fts|.fit|.nc|.gz|.txt|tca.*|extern.*|.rst|.md)$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ".*(.fits|.fts|.fit|.nc|.txt)$"
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: ".*(.fits|.fts|.fit|.gz|.nc|.txt|tca.*)$"
      - id: mixed-line-ending
        exclude: ".*(.fits|.fts|.fit|.gz|.nc|.txt|tca.*)$"
